// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@bagsies.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "description": "Аутентификация сотрудника по номеру телефона и паролю. Возвращает пару JWT-токенов (access + refresh).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Вход сотрудника",
                "parameters": [
                    {
                        "description": "Телефон и пароль",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.loginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Неверный телефон или пароль",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "description": "Инвалидирует refresh-токен. Access-токен продолжает действовать до истечения TTL.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выход из системы",
                "parameters": [
                    {
                        "description": "Refresh-токен для инвалидации",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.logoutRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Токен успешно инвалидирован"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/password/reset": {
            "post": {
                "description": "Отправляет ссылку для сброса пароля на номер телефона сотрудника через WhatsApp (с fallback на SMS).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Запрос на сброс пароля (шаг 1/2)",
                "parameters": [
                    {
                        "description": "Номер телефона",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.requestResetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.messageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Аккаунт неактивен",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Сотрудник не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/password/reset/confirm": {
            "post": {
                "description": "Проверяет one-time токен и устанавливает новый пароль. Все активные сессии инвалидируются.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Подтверждение сброса пароля (шаг 2/2)",
                "parameters": [
                    {
                        "description": "Токен и новый пароль",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.confirmResetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.messageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Токен не найден или истёк",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "Принимает refresh-токен, ротирует его и возвращает новую пару access + refresh токенов.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Обновление токенов",
                "parameters": [
                    {
                        "description": "Refresh-токен",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.refreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.tokensResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Токен не найден или истёк",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "Начинает процесс регистрации владельца организации. Создаёт pending-запрос и отправляет OTP-код на указанный номер телефона.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация владельца",
                "parameters": [
                    {
                        "description": "Данные регистрации",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.registerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Пользователь с таким номером уже существует",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register/resend": {
            "post": {
                "description": "Повторно отправляет OTP-код на телефон. Доступно только если прошёл retry_after интервал с предыдущей отправки.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Повторная отправка OTP",
                "parameters": [
                    {
                        "description": "Номер телефона",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.resendRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.resendResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Pending-запрос не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "429": {
                        "description": "Слишком рано для повторной отправки",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register/verify": {
            "post": {
                "description": "Подтверждает регистрацию владельца OTP-кодом. При успехе создаёт организацию, сотрудника, подписку и возвращает JWT-токены.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Подтверждение регистрации",
                "parameters": [
                    {
                        "description": "Телефон и OTP-код",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.verifyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.tokensResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный код или истёк срок действия",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Pending-запрос не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/verify/{token}": {
            "get": {
                "description": "Возвращает метаданные токена (телефон, назначение, опциональные org/location ID) для отображения на фронтенде. Используется для приглашений и сброса пароля. Не требует авторизации.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Проверить action-токен",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Action-токен",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.verifyActionTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Пустой токен",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Токен не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/bookings": {
            "post": {
                "description": "Создаёт новую запись на услугу для клиента. Запись создаётся в статусе pending и требует подтверждения кодом.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "summary": "Создание записи на услугу",
                "parameters": [
                    {
                        "description": "Данные для записи",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_booking.createRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_booking.createResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Слот уже занят",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/bookings/calendar": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает записи за указанный период с информацией о сотруднике, клиенте, услуге и локации.\nStaff — только свои записи. Manager — записи своей локации. Owner — все записи организации.\nМаксимальный диапазон — 35 дней.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "summary": "Получение календаря записей",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Дата начала (YYYY-MM-DD)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата окончания (YYYY-MM-DD)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "UUID локации (только для Owner)",
                        "name": "location_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "UUID сотрудника (для Manager и Owner)",
                        "name": "employee_id",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Включить отменённые записи (default: false)",
                        "name": "include_cancelled",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_booking.getCalendarResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные параметры или диапазон \u003e 35 дней",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Требуется авторизация",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Подписка приостановлена",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/bookings/slots": {
            "post": {
                "description": "Возвращает доступные временные слоты для записи на услугу, сгруппированные по сотрудникам.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "summary": "Получение доступных слотов для записи",
                "parameters": [
                    {
                        "description": "Параметры поиска слотов",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_booking.getSlotsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_booking.getSlotsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Локация или услуга не найдена",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/bookings/{id}/cancel": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Отменяет существующую запись. Доступно только сотрудникам организации.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "summary": "Отмена записи",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID записи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Причина отмены",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_booking.cancelRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Запись отменена"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Запись не найдена",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/bookings/{id}/confirm": {
            "post": {
                "description": "Подтверждает запись с помощью OTP-кода, присланного в SMS/WhatsApp.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "summary": "Подтверждение записи",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID записи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Код подтверждения",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_booking.confirmRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Запись подтверждена"
                    },
                    "400": {
                        "description": "Неверный код или формат",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Запись не найдена",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/bookings/{id}/resend-otp": {
            "post": {
                "description": "Генерирует и отправляет новый код подтверждения для существующей записи.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "summary": "Повторная отправка кода",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID записи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Код отправлен"
                    },
                    "400": {
                        "description": "Запись уже подтверждена или отменена",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Запись не найдена",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/employees/invite": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Создаёт приглашение и отправляет ссылку для регистрации на номер телефона сотрудника через WhatsApp (с fallback на SMS). Требует авторизации. Owner может приглашать Manager и Staff, Manager — только Staff.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Пригласить сотрудника (шаг 1/2)",
                "parameters": [
                    {
                        "description": "Данные приглашения",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_employee.sendInviteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_employee.sendInviteResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидные данные (телефон, роль, имя)",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Нет прав или подписка приостановлена",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Сотрудник с таким телефоном уже существует",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "429": {
                        "description": "Приглашение уже отправлено (cooldown 60с)",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/employees/invite/confirm": {
            "post": {
                "description": "Сотрудник переходит по ссылке из приглашения, задаёт пароль. Создаётся аккаунт сотрудника, возвращаются JWT-токены. Не требует авторизации.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Подтвердить приглашение (шаг 2/2)",
                "parameters": [
                    {
                        "description": "Токен приглашения и пароль",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_employee.confirmInviteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_employee.confirmInviteResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидные данные",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Токен не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Телефон уже зарегистрирован",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "410": {
                        "description": "Токен истёк",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/employees/invite/resend": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Генерирует новый токен и повторно отправляет ссылку для регистрации. Требует авторизации. Действует cooldown 60 секунд между отправками.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Переотправить приглашение",
                "parameters": [
                    {
                        "description": "Номер телефона приглашённого",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_employee.resendInviteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_employee.resendInviteResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидный телефон",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Нет прав (другая организация)",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Приглашение не найдено",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "429": {
                        "description": "Cooldown ещё не прошёл",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/employees/me": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает информацию о текущем авторизованном сотруднике.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Получение профиля текущего сотрудника",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_employee.getMeResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "404": {
                        "description": "employee_not_found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/locations": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Создаёт новую точку обслуживания для организации. Проверяет лимиты тарифного плана.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "location"
                ],
                "summary": "Создание локации",
                "parameters": [
                    {
                        "description": "Данные локации",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_location.createRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_location.createResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Лимит превышен или подписка приостановлена",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/media/upload": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Создаёт запись о медиафайле и возвращает presigned POST URL для загрузки в S3.\nДопустимые значения purpose: avatars, organizations, locations, services, service-categories.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media"
                ],
                "summary": "Генерация presigned URL для загрузки файла",
                "parameters": [
                    {
                        "description": "Параметры файла",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_media.uploadRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_media.uploadResponse"
                        }
                    },
                    "400": {
                        "description": "invalid_purpose / file_size_limit / empty_filename / unsupported_mime_type",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/media/{id}/confirm": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Проверяет наличие файла в S3 и меняет статус ассета на uploaded.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media"
                ],
                "summary": "Подтверждение загрузки файла",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "asset_not_found / file_not_uploaded",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "409": {
                        "description": "asset_not_pending",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_util.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_auth.confirmResetRequest": {
            "type": "object",
            "properties": {
                "new_password": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_auth.loginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_auth.loginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_auth.logoutRequest": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_auth.messageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_auth.refreshRequest": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_auth.registerRequest": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "plan_code": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_auth.registerResponse": {
            "type": "object",
            "properties": {
                "expires_in": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "retry_after": {
                    "type": "integer"
                }
            }
        },
        "internal_ports_http_handlers_auth.requestResetRequest": {
            "type": "object",
            "properties": {
                "phone": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_auth.resendRequest": {
            "type": "object",
            "properties": {
                "phone": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_auth.resendResponse": {
            "type": "object",
            "properties": {
                "expires_in": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "retry_after": {
                    "type": "integer"
                }
            }
        },
        "internal_ports_http_handlers_auth.tokensResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_auth.verifyActionTokenResponse": {
            "type": "object",
            "properties": {
                "location_id": {
                    "type": "string"
                },
                "organization_id": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "purpose": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_auth.verifyRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_booking.calendarEntryResponse": {
            "type": "object",
            "properties": {
                "appointment_id": {
                    "type": "string"
                },
                "customer_comment": {
                    "type": "string"
                },
                "customer_id": {
                    "type": "string"
                },
                "customer_name": {
                    "type": "string"
                },
                "customer_phone": {
                    "type": "string"
                },
                "duration_minutes": {
                    "type": "integer"
                },
                "employee_id": {
                    "type": "string"
                },
                "employee_name": {
                    "type": "string"
                },
                "end_at": {
                    "type": "string"
                },
                "location_id": {
                    "type": "string"
                },
                "location_name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "service_color": {
                    "type": "string"
                },
                "service_id": {
                    "type": "string"
                },
                "service_name": {
                    "type": "string"
                },
                "start_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_booking.cancelRequest": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_booking.confirmRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_booking.createRequest": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "employee_id": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "location_id": {
                    "type": "string"
                },
                "phone": {
                    "description": "Customer Info",
                    "type": "string"
                },
                "service_id": {
                    "type": "string"
                },
                "start_at": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_booking.createResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_booking.getCalendarResponse": {
            "type": "object",
            "properties": {
                "calendar": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_ports_http_handlers_booking.calendarEntryResponse"
                    }
                }
            }
        },
        "internal_ports_http_handlers_booking.getSlotsRequest": {
            "type": "object",
            "properties": {
                "employee_id": {
                    "description": "optional",
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "location_id": {
                    "type": "string"
                },
                "service_id": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_booking.getSlotsResponse": {
            "type": "object",
            "properties": {
                "duration_minutes": {
                    "type": "integer"
                },
                "location_id": {
                    "type": "string"
                },
                "master_slots": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_ports_http_handlers_booking.masterTimeSlot"
                    }
                },
                "service_id": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_booking.masterTimeSlot": {
            "type": "object",
            "properties": {
                "employee_id": {
                    "type": "string"
                },
                "employee_name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "slots": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_ports_http_handlers_booking.timeSlot"
                    }
                }
            }
        },
        "internal_ports_http_handlers_booking.timeSlot": {
            "type": "object",
            "properties": {
                "end_at": {
                    "type": "string"
                },
                "start_at": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_employee.confirmInviteRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_employee.confirmInviteResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_employee.getMeResponse": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "avatar_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "location_id": {
                    "type": "string"
                },
                "organization_id": {
                    "type": "string"
                },
                "permissions": {
                    "$ref": "#/definitions/internal_ports_http_handlers_employee.permissionsResponse"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_employee.permissionsResponse": {
            "type": "object",
            "properties": {
                "can_manage_location_schedule": {
                    "type": "boolean"
                },
                "can_provide_services": {
                    "type": "boolean"
                }
            }
        },
        "internal_ports_http_handlers_employee.resendInviteRequest": {
            "type": "object",
            "properties": {
                "phone": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_employee.resendInviteResponse": {
            "type": "object",
            "properties": {
                "expires_in": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "retry_after": {
                    "type": "integer"
                }
            }
        },
        "internal_ports_http_handlers_employee.sendInviteRequest": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "location_id": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_employee.sendInviteResponse": {
            "type": "object",
            "properties": {
                "expires_in": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_location.createRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "$ref": "#/definitions/internal_ports_http_handlers_location.createRequestAddress"
                },
                "category_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "schedule_type": {
                    "type": "string"
                },
                "slot_duration_minutes": {
                    "type": "integer"
                }
            }
        },
        "internal_ports_http_handlers_location.createRequestAddress": {
            "type": "object",
            "properties": {
                "building": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "details": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_location.createResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "prompt_org_profile": {
                    "type": "boolean"
                }
            }
        },
        "internal_ports_http_handlers_media.uploadRequest": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string"
                },
                "mime_type": {
                    "type": "string"
                },
                "purpose": {
                    "type": "string",
                    "enum": [
                        "avatars",
                        "organizations",
                        "locations",
                        "services",
                        "service-categories"
                    ]
                },
                "size_bytes": {
                    "type": "integer"
                }
            }
        },
        "internal_ports_http_handlers_media.uploadResponse": {
            "type": "object",
            "properties": {
                "asset_id": {
                    "type": "string"
                },
                "upload_fields": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "upload_url": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Bagsy API",
	Description:      "API для приложения Bagsy",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
