// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@bagsies.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "description": "Выполняет авторизацию пользователя по номеру телефона и паролю",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Авторизация пользователя",
                "parameters": [
                    {
                        "description": "Данные для авторизации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная авторизация",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.loginResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные данные",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Неверный логин или пароль",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "description": "Выполняет выход пользователя из системы и инвалидирует refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выход из системы",
                "parameters": [
                    {
                        "description": "Refresh token для выхода",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.refreshTokensRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный выход"
                    },
                    "400": {
                        "description": "Неверные данные",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "Обновляет токены авторизации",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Обновление токенов авторизации",
                "parameters": [
                    {
                        "description": "Токен авторизации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.refreshTokensRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Токены авторизации успешно обновлены",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.refreshTokensResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный токен",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/staff/register": {
            "post": {
                "description": "Создает нового пользователя (работника) привязанного к точке. Менеджер точки может создавать только в своей точке, менеджер сети - в любой точке своей сети.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация работника на точке",
                "parameters": [
                    {
                        "description": "Данные для регистрации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.registerStaffRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_response.EmptySuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Недостаточно прав для создания работника в указанной точке",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/staff/register/confirm": {
            "post": {
                "description": "Подтверждает регистрацию пользователя(работника)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Подтверждение регистрации работника",
                "parameters": [
                    {
                        "description": "Данные для подтверждения",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.registerConfirmRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Регистрация успешно подтверждена",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_auth.registerConfirmResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные данные",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Неверный или просроченный токен",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/bagsies": {
            "post": {
                "description": "Создает новую бронь на услугу у мастера. Если клиент с указанным номером не существует, создается автоматически. Отправляется SMS/WhatsApp с кодом подтверждения.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bagsies"
                ],
                "summary": "Создание брони на услугу",
                "parameters": [
                    {
                        "description": "Данные для создания брони",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_bagsies.createBagsyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Бронь успешно создана",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_bagsies.createBagsyResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса или валидация не пройдена",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Услуга или мастер не найдены",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Выбранное время уже занято у данного мастера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/bagsies/confirm": {
            "post": {
                "description": "Подтверждает созданную бронь с помощью кода, отправленного клиенту по SMS/WhatsApp",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bagsies"
                ],
                "summary": "Подтверждение брони",
                "parameters": [
                    {
                        "description": "Данные для подтверждения брони",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_bagsies.confirmBagsyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Бронь успешно подтверждена",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_response.EmptySuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса или валидация не пройдена",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Неверный или просроченный код подтверждения",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Бронь не найдена",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/bagsies/resend": {
            "post": {
                "description": "Повторно отправляет код подтверждения брони клиенту по SMS/WhatsApp. Используется если клиент не получил код или код истек.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bagsies"
                ],
                "summary": "Повторная отправка кода подтверждения",
                "parameters": [
                    {
                        "description": "Данные для повторной отправки кода",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_bagsies.resentCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Код успешно отправлен повторно",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_response.EmptySuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса или валидация не пройдена",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Бронь не найдена",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Превышен лимит запросов на отправку кода",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/forms": {
            "post": {
                "description": "Создает новую заявку на сотрудничество",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forms"
                ],
                "summary": "Отправка формы для сотрудничества",
                "parameters": [
                    {
                        "description": "Форма для создания заявки",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_form.clientFormRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное создание заявки",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_response.EmptySuccessResponse"
                        }
                    },
                    "500": {
                        "description": "ошибка",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/staff": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает список пользователей с offset-based пагинацией и учетом прав доступа.\n- NetManager/SelfOwner: пользователи только своей сети\n- Manager: пользователи только своей точки\n- Staff/User: доступ запрещен (403)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получить список пользователей",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Код точки для фильтрации",
                        "name": "point_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Код сети для фильтрации",
                        "name": "network_code",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                "staff",
                                "manager",
                                "net_manager",
                                "self_owner"
                            ],
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Фильтр по ролям",
                        "name": "role",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "Фильтр по номерам телефонов",
                        "name": "phone",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Количество записей на странице (default: 20, max: 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Смещение для пагинации (default: 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "phone",
                            "name",
                            "surname",
                            "point_code",
                            "network_code",
                            "created_at",
                            "updated_at"
                        ],
                        "type": "string",
                        "default": "created_at",
                        "description": "Поле для сортировки",
                        "name": "order_by",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "asc",
                        "description": "Направление сортировки",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список пользователей с пагинацией",
                        "schema": {
                            "$ref": "#/definitions/internal_ports_http_handlers_users.getUsersResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные параметры запроса",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Недостаточно прав для доступа к ресурсу",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_errors.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_Rasikrr_bagsy_backend_monolith_internal_ports_http_response.EmptySuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_auth.loginRequest": {
            "type": "object",
            "required": [
                "password",
                "phone"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 10
                }
            }
        },
        "internal_ports_http_handlers_auth.loginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_auth.refreshTokensRequest": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_auth.refreshTokensResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_auth.registerConfirmRequest": {
            "type": "object",
            "required": [
                "name",
                "password",
                "surname",
                "token"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "minLength": 2
                },
                "password": {
                    "type": "string"
                },
                "surname": {
                    "type": "string",
                    "minLength": 2
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_auth.registerConfirmResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_auth.registerStaffRequest": {
            "type": "object",
            "required": [
                "phone",
                "point_code"
            ],
            "properties": {
                "phone": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 10
                },
                "point_code": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_bagsies.confirmBagsyRequest": {
            "type": "object",
            "required": [
                "bagsy_id",
                "code"
            ],
            "properties": {
                "bagsy_id": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_bagsies.createBagsyRequest": {
            "type": "object",
            "required": [
                "client_phone",
                "comment",
                "master_phone",
                "name",
                "service_id",
                "start_at",
                "surname"
            ],
            "properties": {
                "client_phone": {
                    "type": "string"
                },
                "comment": {
                    "type": "string"
                },
                "master_phone": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "service_id": {
                    "type": "string"
                },
                "start_at": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_bagsies.createBagsyResponse": {
            "type": "object",
            "required": [
                "bagsy_id"
            ],
            "properties": {
                "bagsy_id": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_bagsies.resentCodeRequest": {
            "type": "object",
            "required": [
                "bagsy_id"
            ],
            "properties": {
                "bagsy_id": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_form.clientFormRequest": {
            "type": "object",
            "required": [
                "description",
                "first_name",
                "last_name",
                "phone",
                "role"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 500
                },
                "first_name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "last_name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "internal_ports_http_handlers_users.getUsersResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_ports_http_handlers_users.userDTO"
                    }
                }
            }
        },
        "internal_ports_http_handlers_users.userDTO": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "network_code": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "point_code": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Bagsy API",
	Description:      "API для приложения Bagsy",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
