definitions:
  api.EmptySuccessResponse:
    properties:
      message:
        type: string
    type: object
  api.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  api.SuccessResponse:
    properties:
      data: {}
      message:
        type: string
    type: object
  internal_ports_http_handlers_auth.loginRequest:
    properties:
      password:
        type: string
      phone:
        maxLength: 15
        minLength: 10
        type: string
    required:
    - password
    - phone
    type: object
  internal_ports_http_handlers_auth.loginResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  internal_ports_http_handlers_auth.refreshTokensResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  internal_ports_http_handlers_auth.registerConfirmRequest:
    properties:
      password:
        type: string
      phone:
        maxLength: 15
        minLength: 10
        type: string
    required:
    - phone
    type: object
  internal_ports_http_handlers_auth.registerRequest:
    properties:
      name:
        maxLength: 50
        minLength: 2
        type: string
      phone:
        maxLength: 15
        minLength: 10
        type: string
      point_code:
        type: string
      role:
        type: string
      surname:
        maxLength: 50
        minLength: 2
        type: string
    required:
    - name
    - phone
    - surname
    type: object
  internal_ports_http_handlers_bagsies.createBagsyRequest:
    properties:
      description:
        type: string
      end_at:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      phone:
        type: string
      provider:
        $ref: '#/definitions/internal_ports_http_handlers_bagsies.provider'
      service:
        description: ДОБАВИТЬ ДОМЕЕНУЮ МОДЕЛЬ
        type: string
      start_at:
        type: string
    required:
    - end_at
    - provider
    - start_at
    type: object
  internal_ports_http_handlers_bagsies.provider:
    properties:
      phone:
        maxLength: 15
        minLength: 10
        type: string
      point_code:
        type: string
    required:
    - phone
    - point_code
    type: object
  internal_ports_http_handlers_form.clientFormRequest:
    properties:
      description:
        maxLength: 500
        type: string
      first_name:
        maxLength: 50
        minLength: 2
        type: string
      last_name:
        maxLength: 50
        minLength: 2
        type: string
      phone:
        type: string
      role:
        type: string
    required:
    - description
    - first_name
    - last_name
    - phone
    - role
    type: object
  users.updateRequest:
    properties:
      name:
        type: string
      password:
        type: string
      surname:
        type: string
    type: object
  users.userResponse:
    properties:
      created_at:
        type: string
      is_active:
        type: boolean
      name:
        type: string
      phone:
        type: string
      point_code:
        type: string
      role:
        type: string
      surname:
        type: string
      updated_at:
        type: string
      updated_by:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@bagsy.com
    name: API Support
  description: API для приложения Bagsy
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Bagsy API
  version: "1.0"
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Выполняет авторизацию пользователя по номеру телефона и паролю
      parameters:
      - description: Данные для авторизации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_ports_http_handlers_auth.loginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Успешная авторизация
          schema:
            allOf:
            - $ref: '#/definitions/api.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/internal_ports_http_handlers_auth.loginResponse'
              type: object
        "400":
          description: Неверные данные
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "401":
          description: Неверный логин или пароль
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Авторизация пользователя
      tags:
      - auth
  /api/v1/auth/refresh:
    post:
      consumes:
      - application/json
      description: Обновляет токены авторизации
      parameters:
      - description: Токен авторизации
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Токены авторизации успешно обновлены
          schema:
            allOf:
            - $ref: '#/definitions/api.EmptySuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/internal_ports_http_handlers_auth.refreshTokensResponse'
              type: object
        "400":
          description: Неверный токен
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Обновление токенов авторизации
      tags:
      - auth
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Создает нового пользователя в системе
      parameters:
      - description: Данные для регистрации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_ports_http_handlers_auth.registerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.EmptySuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Регистрация пользователя
      tags:
      - auth
  /api/v1/auth/register/confirm:
    post:
      consumes:
      - application/json
      description: Подтверждает регистрацию пользователя и устанавливает пароль
      parameters:
      - description: Токен подтверждения регистрации
        in: header
        name: Authorization
        required: true
        type: string
      - description: Данные для подтверждения
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_ports_http_handlers_auth.registerConfirmRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Регистрация успешно подтверждена
          schema:
            allOf:
            - $ref: '#/definitions/api.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/internal_ports_http_handlers_auth.loginResponse'
              type: object
        "400":
          description: Неверные данные
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "401":
          description: Неверный или просроченный токен
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Подтверждение регистрации
      tags:
      - auth
  /api/v1/bagsies/create:
    post:
      consumes:
      - application/json
      description: Создает запись к мастеру с определенным кодом точки
      parameters:
      - description: Данные для создания записи
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_ports_http_handlers_bagsies.createBagsyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Создание записи
      tags:
      - bagsies
  /api/v1/forms:
    post:
      consumes:
      - application/json
      description: Создает новую заявку на сотрудничество
      parameters:
      - description: Форма для создания заявки
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_ports_http_handlers_form.clientFormRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Успешное создание заявки
          schema:
            $ref: '#/definitions/api.EmptySuccessResponse'
        "500":
          description: ошибка
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Отправка формы для соотрдничества
      tags:
      - forms
  /api/v1/users/{phone}:
    get:
      description: Возвращает информацию о пользователе по его номеру телефона
      parameters:
      - description: Номер телефона пользователя
        in: path
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Информация о пользователе
          schema:
            allOf:
            - $ref: '#/definitions/api.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/users.userResponse'
              type: object
        "400":
          description: Неверный формат данных
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "404":
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Получение пользователя по номеру телефона
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Обновляет имя, фамилию или пароль пользователя по номеру телефона
      parameters:
      - description: Номер телефона пользователя
        in: path
        name: phone
        required: true
        type: string
      - description: Данные для обновления
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/users.updateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Пользователь успешно обновлен
          schema:
            $ref: '#/definitions/api.EmptySuccessResponse'
        "400":
          description: Неверный формат данных
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "404":
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Обновление данных пользователя
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
