//go:build ignore
// +build ignore

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
	"fmt"
	"os"

	"github.com/mailru/easyjson/gen"

	pkg "github.com/Rasikrr/bagsy_backend_monolith/internal/repositories/access"
)

func main() {
	g := gen.NewGenerator("models_easyjson.go")
	g.SetPkg("access", "github.com/Rasikrr/bagsy_backend_monolith/internal/repositories/access")
	g.Add(pkg.EasyJSON_exporter_orgContextModel(nil))
	if err := g.Run(os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
