// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package points

import (
	json "encoding/json"
	dto "github.com/Rasikrr/bagsy_backend_monolith/internal/ports/http/dto"
	uuid "github.com/google/uuid"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersPoints(in *jlexer.Lexer, out *createPointRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "network_code":
			out.NetworkCode = string(in.String())
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				*out.Description = string(in.String())
			}
		case "category_id":
			out.CategoryID = int(in.Int())
		case "address":
			(out.Address).UnmarshalEasyJSON(in)
		case "schedule":
			if in.IsNull() {
				in.Skip()
				out.Schedule = nil
			} else {
				in.Delim('[')
				if out.Schedule == nil {
					if !in.IsDelim(']') {
						out.Schedule = make([]dto.ScheduleDTO, 0, 1)
					} else {
						out.Schedule = []dto.ScheduleDTO{}
					}
				} else {
					out.Schedule = (out.Schedule)[:0]
				}
				for !in.IsDelim(']') {
					var v1 dto.ScheduleDTO
					(v1).UnmarshalEasyJSON(in)
					out.Schedule = append(out.Schedule, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "photo_ids":
			if in.IsNull() {
				in.Skip()
				out.PhotoIDs = nil
			} else {
				in.Delim('[')
				if out.PhotoIDs == nil {
					if !in.IsDelim(']') {
						out.PhotoIDs = make([]uuid.UUID, 0, 4)
					} else {
						out.PhotoIDs = []uuid.UUID{}
					}
				} else {
					out.PhotoIDs = (out.PhotoIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v2 uuid.UUID
					if data := in.UnsafeBytes(); in.Ok() {
						in.AddError((v2).UnmarshalText(data))
					}
					out.PhotoIDs = append(out.PhotoIDs, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersPoints(out *jwriter.Writer, in createPointRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"network_code\":"
		out.RawString(prefix)
		out.String(string(in.NetworkCode))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		if in.Description == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Description))
		}
	}
	{
		const prefix string = ",\"category_id\":"
		out.RawString(prefix)
		out.Int(int(in.CategoryID))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		(in.Address).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"schedule\":"
		out.RawString(prefix)
		if in.Schedule == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.Schedule {
				if v3 > 0 {
					out.RawByte(',')
				}
				(v4).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"photo_ids\":"
		out.RawString(prefix)
		if in.PhotoIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.PhotoIDs {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.RawText((v6).MarshalText())
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v createPointRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersPoints(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v createPointRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersPoints(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *createPointRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersPoints(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *createPointRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersPoints(l, v)
}
