// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package auth

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (registerRequest) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*registerRequest) UnmarshalJSON([]byte) error        { return nil }
func (registerRequest) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*registerRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_registerRequest *registerRequest

func (registerResponse) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*registerResponse) UnmarshalJSON([]byte) error        { return nil }
func (registerResponse) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*registerResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_registerResponse *registerResponse

func (resendRequest) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*resendRequest) UnmarshalJSON([]byte) error        { return nil }
func (resendRequest) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*resendRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_resendRequest *resendRequest

func (resendResponse) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*resendResponse) UnmarshalJSON([]byte) error        { return nil }
func (resendResponse) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*resendResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_resendResponse *resendResponse

func (verifyRequest) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*verifyRequest) UnmarshalJSON([]byte) error        { return nil }
func (verifyRequest) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*verifyRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_verifyRequest *verifyRequest

func (verifyResponse) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*verifyResponse) UnmarshalJSON([]byte) error        { return nil }
func (verifyResponse) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*verifyResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_verifyResponse *verifyResponse

func (verifyUser) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*verifyUser) UnmarshalJSON([]byte) error        { return nil }
func (verifyUser) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*verifyUser) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_verifyUser *verifyUser
