// Code generated by "enumer -type=BagsyStatus -json -trimprefix BagsyStatus -transform=snake -output bagsy_status_enumer.go"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _BagsyStatusName = "createdcompletedcanceled"

var _BagsyStatusIndex = [...]uint8{0, 7, 16, 24}

const _BagsyStatusLowerName = "createdcompletedcanceled"

func (i BagsyStatus) String() string {
	if i >= BagsyStatus(len(_BagsyStatusIndex)-1) {
		return fmt.Sprintf("BagsyStatus(%d)", i)
	}
	return _BagsyStatusName[_BagsyStatusIndex[i]:_BagsyStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _BagsyStatusNoOp() {
	var x [1]struct{}
	_ = x[BagsyStatusCreated-(0)]
	_ = x[BagsyStatusCompleted-(1)]
	_ = x[BagsyStatusCanceled-(2)]
}

var _BagsyStatusValues = []BagsyStatus{BagsyStatusCreated, BagsyStatusCompleted, BagsyStatusCanceled}

var _BagsyStatusNameToValueMap = map[string]BagsyStatus{
	_BagsyStatusName[0:7]:        BagsyStatusCreated,
	_BagsyStatusLowerName[0:7]:   BagsyStatusCreated,
	_BagsyStatusName[7:16]:       BagsyStatusCompleted,
	_BagsyStatusLowerName[7:16]:  BagsyStatusCompleted,
	_BagsyStatusName[16:24]:      BagsyStatusCanceled,
	_BagsyStatusLowerName[16:24]: BagsyStatusCanceled,
}

var _BagsyStatusNames = []string{
	_BagsyStatusName[0:7],
	_BagsyStatusName[7:16],
	_BagsyStatusName[16:24],
}

// BagsyStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func BagsyStatusString(s string) (BagsyStatus, error) {
	if val, ok := _BagsyStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _BagsyStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to BagsyStatus values", s)
}

// BagsyStatusValues returns all values of the enum
func BagsyStatusValues() []BagsyStatus {
	return _BagsyStatusValues
}

// BagsyStatusStrings returns a slice of all String values of the enum
func BagsyStatusStrings() []string {
	strs := make([]string, len(_BagsyStatusNames))
	copy(strs, _BagsyStatusNames)
	return strs
}

// IsABagsyStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i BagsyStatus) IsABagsyStatus() bool {
	for _, v := range _BagsyStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for BagsyStatus
func (i BagsyStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for BagsyStatus
func (i *BagsyStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("BagsyStatus should be a string, got %s", data)
	}

	var err error
	*i, err = BagsyStatusString(s)
	return err
}
