// Code generated by "enumer -type=MediaStatus -json -trimprefix MediaStatus -transform=snake_case"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _MediaStatusName = "PendingActiveProcessingFailed"

var _MediaStatusIndex = [...]uint8{0, 7, 13, 23, 29}

const _MediaStatusLowerName = "pendingactiveprocessingfailed"

func (i MediaStatus) String() string {
	if i < 0 || i >= MediaStatus(len(_MediaStatusIndex)-1) {
		return fmt.Sprintf("MediaStatus(%d)", i)
	}
	return _MediaStatusName[_MediaStatusIndex[i]:_MediaStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MediaStatusNoOp() {
	var x [1]struct{}
	_ = x[MediaStatusPending-(0)]
	_ = x[MediaStatusActive-(1)]
	_ = x[MediaStatusProcessing-(2)]
	_ = x[MediaStatusFailed-(3)]
}

var _MediaStatusValues = []MediaStatus{MediaStatusPending, MediaStatusActive, MediaStatusProcessing, MediaStatusFailed}

var _MediaStatusNameToValueMap = map[string]MediaStatus{
	_MediaStatusName[0:7]:        MediaStatusPending,
	_MediaStatusLowerName[0:7]:   MediaStatusPending,
	_MediaStatusName[7:13]:       MediaStatusActive,
	_MediaStatusLowerName[7:13]:  MediaStatusActive,
	_MediaStatusName[13:23]:      MediaStatusProcessing,
	_MediaStatusLowerName[13:23]: MediaStatusProcessing,
	_MediaStatusName[23:29]:      MediaStatusFailed,
	_MediaStatusLowerName[23:29]: MediaStatusFailed,
}

var _MediaStatusNames = []string{
	_MediaStatusName[0:7],
	_MediaStatusName[7:13],
	_MediaStatusName[13:23],
	_MediaStatusName[23:29],
}

// MediaStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MediaStatusString(s string) (MediaStatus, error) {
	if val, ok := _MediaStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MediaStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MediaStatus values", s)
}

// MediaStatusValues returns all values of the enum
func MediaStatusValues() []MediaStatus {
	return _MediaStatusValues
}

// MediaStatusStrings returns a slice of all String values of the enum
func MediaStatusStrings() []string {
	strs := make([]string, len(_MediaStatusNames))
	copy(strs, _MediaStatusNames)
	return strs
}

// IsAMediaStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MediaStatus) IsAMediaStatus() bool {
	for _, v := range _MediaStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for MediaStatus
func (i MediaStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MediaStatus
func (i *MediaStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("MediaStatus should be a string, got %s", data)
	}

	var err error
	*i, err = MediaStatusString(s)
	return err
}
