// Code generated by "enumer -type=SortOrder -json -trimprefix SortOrder -transform=snake -output sort_order_enumer.go"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _SortOrderName = "descasc"

var _SortOrderIndex = [...]uint8{0, 4, 7}

const _SortOrderLowerName = "descasc"

func (i SortOrder) String() string {
	if i >= SortOrder(len(_SortOrderIndex)-1) {
		return fmt.Sprintf("SortOrder(%d)", i)
	}
	return _SortOrderName[_SortOrderIndex[i]:_SortOrderIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SortOrderNoOp() {
	var x [1]struct{}
	_ = x[SortOrderDesc-(0)]
	_ = x[SortOrderAsc-(1)]
}

var _SortOrderValues = []SortOrder{SortOrderDesc, SortOrderAsc}

var _SortOrderNameToValueMap = map[string]SortOrder{
	_SortOrderName[0:4]:      SortOrderDesc,
	_SortOrderLowerName[0:4]: SortOrderDesc,
	_SortOrderName[4:7]:      SortOrderAsc,
	_SortOrderLowerName[4:7]: SortOrderAsc,
}

var _SortOrderNames = []string{
	_SortOrderName[0:4],
	_SortOrderName[4:7],
}

// SortOrderString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SortOrderString(s string) (SortOrder, error) {
	if val, ok := _SortOrderNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SortOrderNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SortOrder values", s)
}

// SortOrderValues returns all values of the enum
func SortOrderValues() []SortOrder {
	return _SortOrderValues
}

// SortOrderStrings returns a slice of all String values of the enum
func SortOrderStrings() []string {
	strs := make([]string, len(_SortOrderNames))
	copy(strs, _SortOrderNames)
	return strs
}

// IsASortOrder returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SortOrder) IsASortOrder() bool {
	for _, v := range _SortOrderValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for SortOrder
func (i SortOrder) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for SortOrder
func (i *SortOrder) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("SortOrder should be a string, got %s", data)
	}

	var err error
	*i, err = SortOrderString(s)
	return err
}
