# !!! environment replaced to .env

name: bagsy_backend # name of application

log:
  level: debug # debug, info, warn, error
  add_source: true

metrics:
  enabled: false
  namespace: core
  prometheus:
    port: 9100

http:
  host: 0.0.0.0
  port: 8080
  required: true

grpc:
  host: 0.0.0.0
  port: 3000
  required: false

postgres:
  required: true
  max_conns: 10
  min_conns: 3
  max_idle_conn_time: 10m

redis:
  required: true
  pool_size: 10
  min_idle_conns: 3
  max_idle_conns: 10
  read_timeout: 1m

nats:
  required: false
  queue: example_queue # It is like load balancer, read more about it here: https://docs.nats.io/nats-concepts/core-nats/queue

# If you not provide 'required' field or set it to false, then variable will be ignored
# 'env_name' is name of variable in .env file.
# !!! IMPORTANT !!! .env variables has more priority than config variables
# Available variable types: 'string', 'int', 'float', 'bool', 'duration'

env:
  environment: #dev, prod
    type: "string"
    env_name: "ENVIRONMENT"
    required: true

  config_path:
    type: "string"
    env_name: "CONFIG_PATH"
    required: true

  postgres_dsn:
    type: "string"
    env_name: "POSTGRES_DSN"
    required: true

  redis_host:
    type: "string"
    env_name: "REDIS_HOST"
    required: true

  redis_port:
    type: "int"
    env_name: "REDIS_PORT"
    required: true

  redis_user:
    type: "string"
    env_name: "REDIS_USER"
    required: true

  redis_password:
    type: "string"
    env_name: "REDIS_PASSWORD"
    required: true

  redis_db:
    type: "int"
    env_name: "REDIS_DB"
    required: true

  dev_sms_bot_token:
    type: "string"
    env_name: "DEV_SMS_BOT_TOKEN"
    required: true

  dev_sms_chat_id:
    type: "int"
    env_name: "DEV_SMS_CHAT_ID"
    required: true

  sms_spam_ttl:
    type: "duration"
    env_name: "SMS_SPAM_TTL"
    required: true
    value: "86400s"

  sms_client_login:
    type: "string"
    env_name: "SMS_CLIENT_LOGIN"
    required: true

  sms_client_password:
    type: "string"
    env_name: "SMS_CLIENT_PASSWORD"
    required: true

  auth_code_ttl:
    type: "duration"
    env_name: "AUTH_CODE_TTL"
    required: true
    value: "60s"

  jwt_secret:
    type: "string"
    env_name: "JWT_SECRET"
    required: true

  auth_confirmation_url:
    type: "string"
    env_name: "AUTH_CONFIRMATION_URL"
    value: "https://app.bagsy/ru/invite"
    required: true

  swagger_host:
    type: "string"
    env_name: "SWAGGER_HOST"
    required: true

  swagger_scheme:
    type: "string"
    env_name: "SWAGGER_SCHEME"
    required: true

  whatsapp_api_url:
    type: "string"
    env_name: "WHATSAPP_API_URL"
    required: true

  whatsapp_media_url:
    type: "string"
    env_name: "WHATSAPP_MEDIA_URL"
    required: true

  whatsapp_api_id_instance:
    type: "string"
    env_name: "WHATSAPP_API_ID_INSTANCE"
    required: true

  whatsapp_api_token:
    type: "string"
    env_name: "WHATSAPP_API_TOKEN"
    required: true

  # This is example of variable that do not have value in config but in .env file.
  # by env_name you can get value from .env file
  # !!! IMPORTANT !!! if tou want to add .env variable, first you need to add it to config.yaml
  # Second: you need to declare env_name in config.yaml
  ex_string:
    type: "string"
    env_name: "EX_STRING"
    required: false
