// Code generated by "enumer -type=Color -json -trimprefix Color -transform=snake -output color_enumer.go"; DO NOT EDIT.

package service

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ColorName = "blackgreenredyellowpurpleorangegray"

var _ColorIndex = [...]uint8{0, 5, 10, 13, 19, 25, 31, 35}

const _ColorLowerName = "blackgreenredyellowpurpleorangegray"

func (i Color) String() string {
	if i >= Color(len(_ColorIndex)-1) {
		return fmt.Sprintf("Color(%d)", i)
	}
	return _ColorName[_ColorIndex[i]:_ColorIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ColorNoOp() {
	var x [1]struct{}
	_ = x[ColorBlack-(0)]
	_ = x[ColorGreen-(1)]
	_ = x[ColorRed-(2)]
	_ = x[ColorYellow-(3)]
	_ = x[ColorPurple-(4)]
	_ = x[ColorOrange-(5)]
	_ = x[ColorGray-(6)]
}

var _ColorValues = []Color{ColorBlack, ColorGreen, ColorRed, ColorYellow, ColorPurple, ColorOrange, ColorGray}

var _ColorNameToValueMap = map[string]Color{
	_ColorName[0:5]:        ColorBlack,
	_ColorLowerName[0:5]:   ColorBlack,
	_ColorName[5:10]:       ColorGreen,
	_ColorLowerName[5:10]:  ColorGreen,
	_ColorName[10:13]:      ColorRed,
	_ColorLowerName[10:13]: ColorRed,
	_ColorName[13:19]:      ColorYellow,
	_ColorLowerName[13:19]: ColorYellow,
	_ColorName[19:25]:      ColorPurple,
	_ColorLowerName[19:25]: ColorPurple,
	_ColorName[25:31]:      ColorOrange,
	_ColorLowerName[25:31]: ColorOrange,
	_ColorName[31:35]:      ColorGray,
	_ColorLowerName[31:35]: ColorGray,
}

var _ColorNames = []string{
	_ColorName[0:5],
	_ColorName[5:10],
	_ColorName[10:13],
	_ColorName[13:19],
	_ColorName[19:25],
	_ColorName[25:31],
	_ColorName[31:35],
}

// ColorString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ColorString(s string) (Color, error) {
	if val, ok := _ColorNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ColorNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Color values", s)
}

// ColorValues returns all values of the enum
func ColorValues() []Color {
	return _ColorValues
}

// ColorStrings returns a slice of all String values of the enum
func ColorStrings() []string {
	strs := make([]string, len(_ColorNames))
	copy(strs, _ColorNames)
	return strs
}

// IsAColor returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Color) IsAColor() bool {
	for _, v := range _ColorValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Color
func (i Color) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Color
func (i *Color) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Color should be a string, got %s", data)
	}

	var err error
	*i, err = ColorString(s)
	return err
}
