// Code generated by "enumer -type=Color -json -trimprefix Color -transform=snake -output color_enumer.go"; DO NOT EDIT.

package service

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ColorName = "bluegreenredyellowpurpleorangegray"

var _ColorIndex = [...]uint8{0, 4, 9, 12, 18, 24, 30, 34}

const _ColorLowerName = "bluegreenredyellowpurpleorangegray"

func (i Color) String() string {
	if i >= Color(len(_ColorIndex)-1) {
		return fmt.Sprintf("Color(%d)", i)
	}
	return _ColorName[_ColorIndex[i]:_ColorIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ColorNoOp() {
	var x [1]struct{}
	_ = x[ColorBlue-(0)]
	_ = x[ColorGreen-(1)]
	_ = x[ColorRed-(2)]
	_ = x[ColorYellow-(3)]
	_ = x[ColorPurple-(4)]
	_ = x[ColorOrange-(5)]
	_ = x[ColorGray-(6)]
}

var _ColorValues = []Color{ColorBlue, ColorGreen, ColorRed, ColorYellow, ColorPurple, ColorOrange, ColorGray}

var _ColorNameToValueMap = map[string]Color{
	_ColorName[0:4]:        ColorBlue,
	_ColorLowerName[0:4]:   ColorBlue,
	_ColorName[4:9]:        ColorGreen,
	_ColorLowerName[4:9]:   ColorGreen,
	_ColorName[9:12]:       ColorRed,
	_ColorLowerName[9:12]:  ColorRed,
	_ColorName[12:18]:      ColorYellow,
	_ColorLowerName[12:18]: ColorYellow,
	_ColorName[18:24]:      ColorPurple,
	_ColorLowerName[18:24]: ColorPurple,
	_ColorName[24:30]:      ColorOrange,
	_ColorLowerName[24:30]: ColorOrange,
	_ColorName[30:34]:      ColorGray,
	_ColorLowerName[30:34]: ColorGray,
}

var _ColorNames = []string{
	_ColorName[0:4],
	_ColorName[4:9],
	_ColorName[9:12],
	_ColorName[12:18],
	_ColorName[18:24],
	_ColorName[24:30],
	_ColorName[30:34],
}

// ColorString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ColorString(s string) (Color, error) {
	if val, ok := _ColorNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ColorNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Color values", s)
}

// ColorValues returns all values of the enum
func ColorValues() []Color {
	return _ColorValues
}

// ColorStrings returns a slice of all String values of the enum
func ColorStrings() []string {
	strs := make([]string, len(_ColorNames))
	copy(strs, _ColorNames)
	return strs
}

// IsAColor returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Color) IsAColor() bool {
	for _, v := range _ColorValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Color
func (i Color) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Color
func (i *Color) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Color should be a string, got %s", data)
	}

	var err error
	*i, err = ColorString(s)
	return err
}
