// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package bagsies

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies(in *jlexer.Lexer, out *resentCodeRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "bagsy_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.BagsyID).UnmarshalText(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies(out *jwriter.Writer, in resentCodeRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"bagsy_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.BagsyID).MarshalText())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v resentCodeRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v resentCodeRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *resentCodeRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *resentCodeRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies(l, v)
}
func easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies1(in *jlexer.Lexer, out *masterSlotsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "master_phone":
			out.MasterPhone = string(in.String())
		case "master_name":
			out.MasterName = string(in.String())
		case "slots":
			if in.IsNull() {
				in.Skip()
				out.Slots = nil
			} else {
				in.Delim('[')
				if out.Slots == nil {
					if !in.IsDelim(']') {
						out.Slots = make([]string, 0, 4)
					} else {
						out.Slots = []string{}
					}
				} else {
					out.Slots = (out.Slots)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Slots = append(out.Slots, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies1(out *jwriter.Writer, in masterSlotsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"master_phone\":"
		out.RawString(prefix[1:])
		out.String(string(in.MasterPhone))
	}
	{
		const prefix string = ",\"master_name\":"
		out.RawString(prefix)
		out.String(string(in.MasterName))
	}
	{
		const prefix string = ",\"slots\":"
		out.RawString(prefix)
		if in.Slots == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Slots {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v masterSlotsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v masterSlotsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *masterSlotsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *masterSlotsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies1(l, v)
}
func easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies2(in *jlexer.Lexer, out *getSlotsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "service_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ServiceID).UnmarshalText(data))
			}
		case "point_code":
			out.PointCode = string(in.String())
		case "duration_minutes":
			out.DurationMinutes = int(in.Int())
		case "available_dates":
			if in.IsNull() {
				in.Skip()
				out.AvailableDates = nil
			} else {
				in.Delim('[')
				if out.AvailableDates == nil {
					if !in.IsDelim(']') {
						out.AvailableDates = make([]string, 0, 4)
					} else {
						out.AvailableDates = []string{}
					}
				} else {
					out.AvailableDates = (out.AvailableDates)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					v4 = string(in.String())
					out.AvailableDates = append(out.AvailableDates, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies2(out *jwriter.Writer, in getSlotsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"service_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ServiceID).MarshalText())
	}
	{
		const prefix string = ",\"point_code\":"
		out.RawString(prefix)
		out.String(string(in.PointCode))
	}
	{
		const prefix string = ",\"duration_minutes\":"
		out.RawString(prefix)
		out.Int(int(in.DurationMinutes))
	}
	{
		const prefix string = ",\"available_dates\":"
		out.RawString(prefix)
		if in.AvailableDates == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.AvailableDates {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getSlotsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getSlotsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getSlotsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getSlotsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies2(l, v)
}
func easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies3(in *jlexer.Lexer, out *getSlotsRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "point_code":
			out.PointCode = string(in.String())
		case "service_id":
			out.ServiceID = string(in.String())
		case "master_phone":
			if in.IsNull() {
				in.Skip()
				out.MasterPhone = nil
			} else {
				if out.MasterPhone == nil {
					out.MasterPhone = new(string)
				}
				*out.MasterPhone = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies3(out *jwriter.Writer, in getSlotsRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"point_code\":"
		out.RawString(prefix[1:])
		out.String(string(in.PointCode))
	}
	{
		const prefix string = ",\"service_id\":"
		out.RawString(prefix)
		out.String(string(in.ServiceID))
	}
	{
		const prefix string = ",\"master_phone\":"
		out.RawString(prefix)
		if in.MasterPhone == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.MasterPhone))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getSlotsRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getSlotsRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getSlotsRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getSlotsRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies3(l, v)
}
func easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies4(in *jlexer.Lexer, out *getSlotsForDayResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "service_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ServiceID).UnmarshalText(data))
			}
		case "point_code":
			out.PointCode = string(in.String())
		case "date":
			out.Date = string(in.String())
		case "duration_minutes":
			out.DurationMinutes = int(in.Int())
		case "masters":
			if in.IsNull() {
				in.Skip()
				out.Masters = nil
			} else {
				in.Delim('[')
				if out.Masters == nil {
					if !in.IsDelim(']') {
						out.Masters = make([]masterSlotsResponse, 0, 1)
					} else {
						out.Masters = []masterSlotsResponse{}
					}
				} else {
					out.Masters = (out.Masters)[:0]
				}
				for !in.IsDelim(']') {
					var v7 masterSlotsResponse
					(v7).UnmarshalEasyJSON(in)
					out.Masters = append(out.Masters, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies4(out *jwriter.Writer, in getSlotsForDayResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"service_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ServiceID).MarshalText())
	}
	{
		const prefix string = ",\"point_code\":"
		out.RawString(prefix)
		out.String(string(in.PointCode))
	}
	{
		const prefix string = ",\"date\":"
		out.RawString(prefix)
		out.String(string(in.Date))
	}
	{
		const prefix string = ",\"duration_minutes\":"
		out.RawString(prefix)
		out.Int(int(in.DurationMinutes))
	}
	{
		const prefix string = ",\"masters\":"
		out.RawString(prefix)
		if in.Masters == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Masters {
				if v8 > 0 {
					out.RawByte(',')
				}
				(v9).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getSlotsForDayResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getSlotsForDayResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getSlotsForDayResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getSlotsForDayResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies4(l, v)
}
func easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies5(in *jlexer.Lexer, out *getSlotsForDayRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "point_code":
			out.PointCode = string(in.String())
		case "service_id":
			out.ServiceID = string(in.String())
		case "date":
			out.Date = string(in.String())
		case "master_phone":
			if in.IsNull() {
				in.Skip()
				out.MasterPhone = nil
			} else {
				if out.MasterPhone == nil {
					out.MasterPhone = new(string)
				}
				*out.MasterPhone = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies5(out *jwriter.Writer, in getSlotsForDayRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"point_code\":"
		out.RawString(prefix[1:])
		out.String(string(in.PointCode))
	}
	{
		const prefix string = ",\"service_id\":"
		out.RawString(prefix)
		out.String(string(in.ServiceID))
	}
	{
		const prefix string = ",\"date\":"
		out.RawString(prefix)
		out.String(string(in.Date))
	}
	{
		const prefix string = ",\"master_phone\":"
		out.RawString(prefix)
		if in.MasterPhone == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.MasterPhone))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getSlotsForDayRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getSlotsForDayRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getSlotsForDayRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getSlotsForDayRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies5(l, v)
}
func easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies6(in *jlexer.Lexer, out *createBagsyResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "bagsy_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.BagsyID).UnmarshalText(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies6(out *jwriter.Writer, in createBagsyResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"bagsy_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.BagsyID).MarshalText())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v createBagsyResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v createBagsyResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *createBagsyResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *createBagsyResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies6(l, v)
}
func easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies7(in *jlexer.Lexer, out *createBagsyRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "service_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ServiceID).UnmarshalText(data))
			}
		case "master_phone":
			out.MasterPhone = string(in.String())
		case "start_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.StartAt).UnmarshalJSON(data))
			}
		case "client_phone":
			out.ClientPhone = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "surname":
			out.Surname = string(in.String())
		case "comment":
			if in.IsNull() {
				in.Skip()
				out.Comment = nil
			} else {
				if out.Comment == nil {
					out.Comment = new(string)
				}
				*out.Comment = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies7(out *jwriter.Writer, in createBagsyRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"service_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ServiceID).MarshalText())
	}
	{
		const prefix string = ",\"master_phone\":"
		out.RawString(prefix)
		out.String(string(in.MasterPhone))
	}
	{
		const prefix string = ",\"start_at\":"
		out.RawString(prefix)
		out.Raw((in.StartAt).MarshalJSON())
	}
	{
		const prefix string = ",\"client_phone\":"
		out.RawString(prefix)
		out.String(string(in.ClientPhone))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"surname\":"
		out.RawString(prefix)
		out.String(string(in.Surname))
	}
	{
		const prefix string = ",\"comment\":"
		out.RawString(prefix)
		if in.Comment == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Comment))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v createBagsyRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v createBagsyRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *createBagsyRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *createBagsyRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies7(l, v)
}
func easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies8(in *jlexer.Lexer, out *confirmBagsyRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "bagsy_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.BagsyID).UnmarshalText(data))
			}
		case "code":
			out.Code = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies8(out *jwriter.Writer, in confirmBagsyRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"bagsy_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.BagsyID).MarshalText())
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v confirmBagsyRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v confirmBagsyRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *confirmBagsyRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *confirmBagsyRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrBagsyBackendMonolithInternalPortsHttpHandlersBagsies8(l, v)
}
